# Generated by Django 3.2.8 on 2021-12-08 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0018_company_size'),
        ('users', '0002_auto_20211207_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='offers_applied',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_applied', models.ManyToManyField(blank=True, to='job_listings.Job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
