# Generated by Django 3.2.8 on 2021-11-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0003_auto_20211123_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='establishment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
