# Generated by Django 3.2.8 on 2021-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0004_auto_20211024_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('establishment', models.DateTimeField(blank=True)),
                ('website_url', models.CharField(max_length=100)),
            ],
        ),
    ]
