# Generated by Django 3.2.8 on 2021-10-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0006_auto_20211024_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-establishment',)},
        ),
    ]
