# Generated by Django 3.2.8 on 2021-11-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0008_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='slug', max_length=250, unique_for_date='published'),
            preserve_default=False,
        ),
    ]
