# Generated by Django 3.2.8 on 2021-11-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0010_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True, unique_for_date='published'),
        ),
    ]
