# Generated by Django 3.2.8 on 2021-11-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0012_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_listings.company'),
        ),
    ]
