# Generated by Django 3.2.8 on 2021-11-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0015_auto_20211129_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='my-company', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='job-title', max_length=250),
            preserve_default=False,
        ),
    ]
