# Generated by Django 3.2.8 on 2021-12-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0017_auto_20211130_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
